name: Publish Library

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish library
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Build library
        run: ./gradlew assemble --scan

      - name: Publish to MavenCentral
        run: |
          ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}